/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    TodoContainer: typeof import('./src/components/todo/TodoContainer.vue')['default']
    TodoFooter: typeof import('./src/components/TodoFooter.vue')['default']
    TodoForm: typeof import('./src/components/todo/TodoForm.vue')['default']
    TodoHeader: typeof import('./src/components/TodoHeader.vue')['default']
    TodoMain: typeof import('./src/components/TodoMain.vue')['default']
  }
}
